#!/bin/bash
###########################################################
#                                                         #                  
#  Released under the GNU Public License                  #                  
#                                                         #                  
#  Script     :  "echo_wavplay                            #
#  Author     :  Marcus Xenakis WA2DCI                    #
#  Version    :  .15 Beta                                 #
#  Date       :  3/28/03                                  #
#  About      :  Plays EchoIRLP wav files                 #
#                                                         #
###########################################################

# Make sure we are user repeater!!!
if [ `/usr/bin/whoami` != "repeater" ] ; then
  echo This program must be run as user REPEATER!
  exit 1
fi

# Make sure we have sourced the environment file
if [ "$RUN_ENV" != "TRUE" ] ; then
  . /home/irlp/custom/environment
fi

# Make sure we have sourced the EchoLinux environment file
if [ "$ECHO_ENV" != "TRUE" ] ; then
  echo "You must add EchoIRLP environment variables to the environment file."
  echo "Check your installtion instructions."
  exit 1
fi

if [ "$#" = "0" ] ; then exit 1; fi

while [ -n "$1" ] ; do
  WAVFILES="$WAVFILES $ECHO_AUDIO/$1.wav"
  shift
done

$BIN/forcekey
# Allows users to set the TXDELAY in the environment file
usleep ${TXDELAY:-250000}
$BIN/play $WAVFILES > /dev/null 2>&1
usleep 250000
$BIN/forceunkey

exit 0
