#!/bin/bash

GT=">"
# Make sure we are user repeater!!!
if [ "`/usr/bin/whoami`" != "repeater" ] ; then
  echo "This program must be run as user REPEATER!"
  exit 1
fi

# Make sure we have sourced the environment file
if [ "$RUN_ENV" != "TRUE" ] ; then
  echo "You must source the environment file first. Do this by running:"
  echo ". /home/irlp/custom/environment"
  exit 1
fi

# Make sure we have sourced the environment file
if [ "$ECHO_ENV" != "TRUE" ] ; then
  echo "You must source the environment file first. Do this by running:"
  echo ". /home/irlp/custom/environment"
  exit 1
fi

if [ -f "$LOCAL"/echoidle ] ; then
  # System is set to idle on Echolink connection, have
  # Incoming IRLP call, kill Echolink connections and connect IRLP, leaving
  # connected Echolink stations connected.
  
"$ECHO_TBD_COMMAND" -q message "$ECHO_MYCALL$GT Incoming IRLP call from $1, back later!"
killall imike
killall imike_PCI

fi
