#!/bin/bash
#syntax echo_idle on|off

GT=">"
# Make sure we are user repeater!!!
if [ "`/usr/bin/whoami`" != "repeater" ] ; then
  echo "This program must be run as user REPEATER!"
  exit 1
fi

# Make sure we have sourced the environment file
if [ "$RUN_ENV" != "TRUE" ] ; then
  echo "You must source the environment file first. Do this by running:"
  echo ". /home/irlp/custom/environment"
  exit 1
fi

# Make sure we have sourced the environment file
if [ "$ECHO_ENV" != "TRUE" ] ; then
  echo "You must source the environment file first. Do this by running:"
  echo ". /home/irlp/custom/environment"
  exit 1
fi


if [ "$1" = "on" ] ; then
  touch $LOCAL/echoidle
  if [ -f "$LOCAL"/active ] ; then
    killall ispeaker
    killall ispeaker_PCI
    $SCRIPT/wavplay linkon
    $SCRIPT/sfswrapper
  else
    $SCRIPT/wavplay linkon
    "$ECHO_SCRIPT"/echoidle_wake
  fi
elif [ "$1" = "off" ] ; then
  rm -f $LOCAL/echoidle

  killall ispeaker
  killall ispeaker_PCI
  if [ ! -f "$LOCAL"/active ] ; then
    killall ispeaker
    killall ispeaker_PCI
    $SCRIPT/wavplay linkoff
    $SCRIPT/sfswrapper
  else
    $SCRIPT/wavplay linkoff
  fi
  if [ ! -f "LOCAL"/echo_active ] ; then
   "$ECHO_TBD_COMMAND" disconnect all
  fi
else 
  echo "Syntax:  echo_idle on|off"
fi
