#!/bin/bash
###########################################################
#                                                         #                  
#  Released under the GNU Public License                  #                  
#                                                         #                  
#  Script   :  echo_disable                               #
#  Author   :  Marcus Xenakis WA2DCI                      #
#  Version  :  .13 Beta                                   #
#  Date     :  3/15/03                                    #
#  About    :  This sripts disables EchoLink              #  
#  Modified :  3/15/03 to use forcekey/forceunkey         #
#                                                         #
###########################################################

# Make sure we have sourced the environment file
if [ "$RUN_ENV" != "TRUE" ] ; then
  . /home/irlp/custom/environment
fi

# Make sure we have sourced the EchoLinux environment file
if [ "$ECHO_ENV" != "TRUE" ] ; then
  echo "You must add EchoIRLP environment variables to the environment file."
  echo "Check your installtion instructions."
  exit 1
fi

# Exits if node is not enabled
if [ -f "$LOCAL"/echo_enable ] ; then 

  rm "$LOCAL"/echo_enable
  "$BIN"/forcekey
  usleep ${TXDELAY:-250000}
  play "$ECHO_AUDIO"/echodisabled.wav
  usleep 250000
  "$BIN"/forceunkey

else 

  echo "The node is already disabled."
     
fi

exit 0
